@extends('layouts.auth_app')
@section('content')
<?php
$currentuserid = Auth::user()->id;
$role = DB::table('user_roles')->where('user_id', $currentuserid)->first();
$role_id = $role->role_id;
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-6">
        <h2>Approval {{ $data['heading'] }} Cases </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">Home</a>
            </li>
            <li class="active">
                <strong>Approval {{ $data['heading'] }} Cases</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
	        <div class="ibox float-e-margins">
                <div class="ibox-title">
	                <h5>Approval {{ $data['heading'] }} Cases List</h5>
	                <div class="ibox-tools">
	                    <a class="collapse-link">
	                        <i class="fa fa-chevron-up"></i>
	                    </a>
	                </div>
	            </div>

	            <div class="ibox-content">

                    <div class="table-responsive">
	                    <table class="table table-striped table-bordered table-hover dataTables-example">
	                        <thead>
	                            <tr>
                                    <th>#</th>
                                    <th>Action</th>
                                    <th>Case ID</th>
                                    <th>Customer Name</th>
                                    <th>UserName</th>
                                    <th>Details in Tally</th>
                                    <th>Generated By</th>
                                    <th>Converted By</th>
                                    <th>Phone</th>
                                    <th>Location</th>
                                    <th>Commodity</th>
                                    <th>Approx Quantity(Qtl)</th>
                                    <th>Terminal</th>
                                    <th>Purpose</th>
                                    <th>Created On</th>
	                            </tr>
	                        </thead>
	                        <tbody>
                                @foreach($case_gen as $key => $lead)
	                                <tr class="gradeX">
                                        <td>{{ ++$key }}</td>
                                        <td>
                                            <a data-id="{!! $lead->case_id !!}" id='{!! $lead->cust_fname." ".$lead->cust_lname !!}' class="setPrice btn-warning btn btn-xs">Approve</a>
                                        </td>
                                        <td>{!! $lead->case_id !!}</td>
                                        <td>{!! $lead->cust_fname." ".$lead->cust_lname !!}</td>
                                        <td><b>User : </b>{!! ($lead->fpo_user_id)?$lead->fpo_user_id:'N/A' !!}<br><b>Gatepass/CDF Name : </b>{!! ($lead->gate_pass_cdf_user_name)?$lead->gate_pass_cdf_user_name:'N/A' !!}<br><b>Coldwin Name : </b>{!! ($lead->coldwin_name)?$lead->coldwin_name:'N/A' !!}</td>
                                        <td><b>Purchase Details: </b>{!! ($lead->purchase_name)?$lead->purchase_name:'N/A' !!}<br><b>Loan Details : </b>{!! ($lead->loan_name)?$lead->loan_name:'N/A' !!}<br><b>Sale Details : </b>{!! ($lead->sale_name)?$lead->sale_name:'N/A' !!}</td>
                                        <td>{!! $lead->lead_gen_fname." ".$lead->lead_gen_lname !!}</td>
                                        <td>{!! $lead->lead_conv_fname ." ".$lead->lead_conv_lname !!}</td>

                                        <td>{!! $lead->phone !!}</td>
                                        <td>{!! $lead->location !!}</td>
                                        <td>{!! $lead->cate_name ." (".$lead->commodity_type.")"  !!}</td>
                                        <td>{!! $lead->total_weight !!}</td>
                                        <td>{!! $lead->terminal_name !!}</td>
                                        <td>{!! $lead->purpose !!}</td>
                                        <td>{!! date('d M Y', strtotime($lead->created_at)) !!}</td>
	                                </tr>
                                @endforeach
	                        </tbody>
	                    </table>
	                </div>

	            </div>
	        </div>
    	</div>
    </div>
</div>

<!-- Add User Employee by Admin -->
<div id="setCasePrice" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Approve Case</h4>
            </div>
            <div class="modal-body">
                <h4 class="text-primary col-md-6 p-0">Case ID : <b style="color:green;" id="case_id_val"></b></h4>
                <h4 class="text-primary col-md-6 p-0 text-right">Customer Name : <b style="color:green;" id="cust_name"></b></h4>
                {!! Form::open(array('url' => 'caseApprove', 'files' => true, 'class' => "contact_us_form", 'id' => 'empForm')) !!}
                {!! Form::hidden('case_id', '',array('id' => 'hidden_case_id')) !!}
                    @csrf
                    
                    <div class="row">
                        <div class="col-md-12">
                            {!! Form::label('notes', 'Notes', ['class' => 'm-t-20  col-form-label text-md-right']) !!}
                            {!! Form::textarea('notes', '', ['class' => 'form-control', 'autocomplete' => 'off', 'required' => 'required', 'rows' => '6', 'placeholder' => 'Enter Notes']) !!}

                            @if($errors->has('notes'))
                                <span class="text-red" role="alert">
                                    <strong class="red">{{ $errors->first('notes') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {!! Form::submit('Save / Final Approve', ['class' => 'btn btn-info m-t-20 form-control b-info']) !!}
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.setPrice').on('click', function(){
            var case_id = $(this).attr('data-id');
            var name = $(this).attr('id');
            $('#case_id_val').html(case_id);
            $('#hidden_case_id').val(case_id);
            $('#cust_name').html(name);
            $('#setCasePrice').modal('show');
        });
    });
</script>
@endsection
