@extends('layouts.auth_app')
@section('content')
<?php
$currentuserid = Auth::user()->id;
$role = DB::table('user_roles')->where('user_id', $currentuserid)->first();
$role_id = $role->role_id;
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-6">
        <h2>All Completed Cases </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">Home</a>
            </li>
            <li class="active">
                <strong>Completed Cases</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
	        <div class="ibox float-e-margins">
                <div class="ibox-title">
	                <h5>Completed Cases List</h5>
	                <div class="ibox-tools">
	                    <a class="collapse-link">
	                        <i class="fa fa-chevron-up"></i>
	                    </a>
	                </div>
	            </div>

	            <div class="ibox-content">
                    @if(session('status'))
                        <div class="alert alert-success alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(session('error'))
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('error') }}
                        </div>
                    @endif
                    <div class="table-responsive">
	                    <table class="table table-striped table-bordered table-hover dataTables-example">
	                        <thead>
	                            <tr>
                                    <th>#</th>
                                    <th>Case ID</th>
                                    <th>Customer Name</th>
                                    <th>UserName</th>
                                    <th>Details in Tally</th>
                                    <th>Generated By</th>
                                    <th>Converted By</th>
                                    <th>Phone</th>
                                    <th>Location</th>
                                    <th>Commodity</th>
                                    <th>Approx Quantity(Qtl)</th>
                                    <th>Terminal</th>
                                    <th>In / Out</th>
                                    <th>Purpose</th>
                                    <th>Created On</th>
                                    <th>Closed On</th>
	                            </tr>
	                        </thead>
	                        <tbody>
                                @foreach($case_gen as $key => $case)
	                                <tr class="gradeX">
                                        <td>{{ ++$key }}</td>
                                        <td><a href="{{ route('viewCase', ['case_id' => $case->case_id]) }}">{!! $case->case_id !!}</a></td>
                                        <!-- <td><a>{!! $case->case_id !!}</a></td> -->

                                        <td>{!! $case->cust_fname." ".$case->cust_lname !!}</td>
                                        <td><b>User : </b>{!! ($case->fpo_user_id)?$case->fpo_user_id:'N/A' !!}<br><b>Gatepass/CDF Name : </b>{!! ($case->gate_pass_cdf_user_name)?$case->gate_pass_cdf_user_name:'N/A' !!}<br><b>Coldwin Name : </b>{!! ($case->coldwin_name)?$case->coldwin_name:'N/A' !!}</td>
                                        <td><b>Purchase Details: </b>{!! ($case->purchase_name)?$case->purchase_name:'N/A' !!}<br><b>Loan Details : </b>{!! ($case->loan_name)?$case->loan_name:'N/A' !!}<br><b>Sale Details : </b>{!! ($case->sale_name)?$case->sale_name:'N/A' !!}</td>
                                        <td>{!! $case->lead_gen_fname." ".$case->lead_gen_lname !!}</td>
                                        <td>{!! $case->lead_conv_fname ." ".$case->lead_conv_lname !!}</td>
                                        <td>{!! $case->phone !!}</td>
                                        <td>{!! $case->location !!}</td>
                                        <td>{!! $case->cate_name ." (".$case->commodity_type.")"  !!}</td>
                                        <td>{!! $case->total_weight !!}</td>
                                        <td>{!! $case->terminal_name !!}</td>
                                        <td>{!! $case->in_out !!}</td>
                                        <td>{!! $case->purpose !!}</td>
                                        <td>{!! date('d M Y', strtotime($case->created_at)) !!}</td>
                                        <td>{!! date('d M Y', strtotime($case->updated_at)) !!}</td>
	                                </tr>
                                @endforeach
	                        </tbody>
	                    </table>
	                </div>

	            </div>
	        </div>
    	</div>
    </div>
</div>

@endsection
