@extends('layouts.auth_app')
@section('content')
<?php
$currentuserid = Auth::user()->id;
$role = DB::table('user_roles')->where('user_id', $currentuserid)->first();
$role_id = $role->role_id;
?>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-6">
        <h2>All Completed Cases </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">Home</a>
            </li>
            <li class="active">
                <strong>Completed Cases</strong>
            </li>
        </ol>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
	        <div class="ibox float-e-margins">
                <div class="ibox-title">
	                <h5>Completed Cases List</h5>
	                <div class="ibox-tools">
	                    <a class="collapse-link">
	                        <i class="fa fa-chevron-up"></i>
	                    </a>
	                </div>
	            </div>

	            <div class="ibox-content">
                    @if(session('status'))
                        <div class="alert alert-success alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(session('error'))
                        <div class="alert alert-danger alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            {{ session('error') }}
                        </div>
                    @endif
                    <div class="table-responsive">
	                    <table class="table table-striped table-bordered table-hover completed_cases_datatable">
	                        <thead>
	                            <tr>
                                    <th>#</th>
                                    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Case_ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                                    <th>Customer Name</th>
                                    <th>UserName</th>
                                    <th>&nbsp;&nbsp;&nbsp;Details_in_Tally&nbsp;&nbsp;&nbsp;</th>
                                    <th>Generated By</th>
                                    <th>Converted By</th>
                                    <th>Phone</th>
                                    <th>Location</th>
                                    <th>Commodity</th>
                                    <th>Approx Quantity(Qtl)</th>
                                    <th>Terminal</th>
                                    <th>In / Out</th>
                                    <th>Purpose</th>
                                    <th>Created On</th>
                                    <th>Closed On</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                        </tbody>
	                    </table>
	                </div>

	            </div>
	        </div>
    	</div>
    </div>
</div>
<script type="text/javascript">    
    $(document).ready(function(){
        var pTable = $('.completed_cases_datatable').dataTable({
            "bDestroy": true,
            "processing": true,
            "serverSide": true,
            "ajax": "{{ route('getCompletedCasesByAjax') }}",
            "columns": [
                {data: 'id', name: 'id'},
                {data: 'caseid', name: 'caseid'},
                {data: 'customer_name', name: 'customer_name'},
                {data: 'users', name: 'users'},
                {data: 'purchase_details', name: 'purchase_details'},
                {data: 'generated_by', name: 'generated_by'},
                {data: 'converted_by', name: 'converted_by'},
                {data: 'phone', name: 'phone'},
                {data: 'location', name: 'location'},
                {data: 'commodity', name: 'commodity'},
                {data: 'total_weight', name: 'total_weight'},
                {data: 'terminal_name', name: 'terminal_name'},
                {data: 'in_out', name: 'in_out'},
                {data: 'purpose', name: 'purpose'},
                {data: 'created_on', name: 'created_on'},
                {data: 'closed_on', name: 'closed_on'},
            ],
        });
    });
</script>
@endsection
